/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_BandCombinationParameters_v1630_H_
#define	_BandCombinationParameters_v1630_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <NativeEnumerated.h>
#include "ScalingFactorSidelink-r16.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BandCombinationParameters_v1630__interBandPowerSharingSyncDAPS_r16 {
	BandCombinationParameters_v1630__interBandPowerSharingSyncDAPS_r16_supported	= 0
} e_BandCombinationParameters_v1630__interBandPowerSharingSyncDAPS_r16;
typedef enum BandCombinationParameters_v1630__interBandPowerSharingAsyncDAPS_r16 {
	BandCombinationParameters_v1630__interBandPowerSharingAsyncDAPS_r16_supported	= 0
} e_BandCombinationParameters_v1630__interBandPowerSharingAsyncDAPS_r16;

/* BandCombinationParameters-v1630 */
typedef struct BandCombinationParameters_v1630 {
	BIT_STRING_t	*v2x_SupportedTxBandCombListPerBC_v1630;	/* OPTIONAL */
	BIT_STRING_t	*v2x_SupportedRxBandCombListPerBC_v1630;	/* OPTIONAL */
	struct BandCombinationParameters_v1630__scalingFactorTxSidelink_r16 {
		A_SEQUENCE_OF(ScalingFactorSidelink_r16_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *scalingFactorTxSidelink_r16;
	struct BandCombinationParameters_v1630__scalingFactorRxSidelink_r16 {
		A_SEQUENCE_OF(ScalingFactorSidelink_r16_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *scalingFactorRxSidelink_r16;
	long	*interBandPowerSharingSyncDAPS_r16;	/* OPTIONAL */
	long	*interBandPowerSharingAsyncDAPS_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BandCombinationParameters_v1630_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_interBandPowerSharingSyncDAPS_r16_8;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_interBandPowerSharingAsyncDAPS_r16_10;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_BandCombinationParameters_v1630;
extern asn_SEQUENCE_specifics_t asn_SPC_BandCombinationParameters_v1630_specs_1;
extern asn_TYPE_member_t asn_MBR_BandCombinationParameters_v1630_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _BandCombinationParameters_v1630_H_ */
#include <asn_internal.h>
