/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_CandidateServingFreqListNR_r15_H_
#define	_CandidateServingFreqListNR_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ARFCN-ValueNR-r15.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CandidateServingFreqListNR-r15 */
typedef struct CandidateServingFreqListNR_r15 {
	A_SEQUENCE_OF(ARFCN_ValueNR_r15_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CandidateServingFreqListNR_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CandidateServingFreqListNR_r15;
extern asn_SET_OF_specifics_t asn_SPC_CandidateServingFreqListNR_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_CandidateServingFreqListNR_r15_1[1];
extern asn_per_constraints_t asn_PER_type_CandidateServingFreqListNR_r15_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CandidateServingFreqListNR_r15_H_ */
#include <asn_internal.h>
