/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_DL_UM_RLC_r15_H_
#define	_DL_UM_RLC_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SN-FieldLength-r15.h"
#include "T-Reordering.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DL-UM-RLC-r15 */
typedef struct DL_UM_RLC_r15 {
	SN_FieldLength_r15_t	 sn_FieldLength_r15;
	T_Reordering_t	 t_Reordering_r15;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DL_UM_RLC_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DL_UM_RLC_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_DL_UM_RLC_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_DL_UM_RLC_r15_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _DL_UM_RLC_r15_H_ */
#include <asn_internal.h>
