/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_FailureInformation_r16_IEs_H_
#define	_FailureInformation_r16_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FailureInformation_r16_IEs__failureType_r16 {
	FailureInformation_r16_IEs__failureType_r16_duplication	= 0,
	FailureInformation_r16_IEs__failureType_r16_dapsHO_failure	= 1,
	FailureInformation_r16_IEs__failureType_r16_spare2	= 2,
	FailureInformation_r16_IEs__failureType_r16_spare1	= 3
} e_FailureInformation_r16_IEs__failureType_r16;

/* Forward declarations */
struct FailedLogicalChannelIdentity_r16;

/* FailureInformation-r16-IEs */
typedef struct FailureInformation_r16_IEs {
	struct FailedLogicalChannelIdentity_r16	*failedLogicalChannelIdentity_r16;	/* OPTIONAL */
	long	*failureType_r16;	/* OPTIONAL */
	struct FailureInformation_r16_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FailureInformation_r16_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_failureType_r16_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_FailureInformation_r16_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_FailureInformation_r16_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_FailureInformation_r16_IEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _FailureInformation_r16_IEs_H_ */
#include <asn_internal.h>
