/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#include "FailedLogicalChannelIdentity-r16.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_logicalChannelIdentity_r16_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1L && value <= 10L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_logicalChannelIdentityExt_r16_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 32L && value <= 38L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_cellGroupIndication_r16_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_logicalChannelIdentity_r16_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  1,  10 }	/* (1..10) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_logicalChannelIdentityExt_r16_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  32,  38 }	/* (32..38) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_cellGroupIndication_r16_value2enum_2[] = {
	{ 0,	2,	"mn" },
	{ 1,	2,	"sn" }
};
static const unsigned int asn_MAP_cellGroupIndication_r16_enum2value_2[] = {
	0,	/* mn(0) */
	1	/* sn(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_cellGroupIndication_r16_specs_2 = {
	asn_MAP_cellGroupIndication_r16_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_cellGroupIndication_r16_enum2value_2,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_cellGroupIndication_r16_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cellGroupIndication_r16_2 = {
	"cellGroupIndication-r16",
	"cellGroupIndication-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_cellGroupIndication_r16_tags_2,
	sizeof(asn_DEF_cellGroupIndication_r16_tags_2)
		/sizeof(asn_DEF_cellGroupIndication_r16_tags_2[0]) - 1, /* 1 */
	asn_DEF_cellGroupIndication_r16_tags_2,	/* Same as above */
	sizeof(asn_DEF_cellGroupIndication_r16_tags_2)
		/sizeof(asn_DEF_cellGroupIndication_r16_tags_2[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_cellGroupIndication_r16_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_cellGroupIndication_r16_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_FailedLogicalChannelIdentity_r16_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FailedLogicalChannelIdentity_r16, cellGroupIndication_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_cellGroupIndication_r16_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"cellGroupIndication-r16"
		},
	{ ATF_POINTER, 2, offsetof(struct FailedLogicalChannelIdentity_r16, logicalChannelIdentity_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_logicalChannelIdentity_r16_constr_5,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_logicalChannelIdentity_r16_constraint_1
		},
		0, 0, /* No default value */
		"logicalChannelIdentity-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct FailedLogicalChannelIdentity_r16, logicalChannelIdentityExt_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_logicalChannelIdentityExt_r16_constr_6,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_logicalChannelIdentityExt_r16_constraint_1
		},
		0, 0, /* No default value */
		"logicalChannelIdentityExt-r16"
		},
};
static const int asn_MAP_FailedLogicalChannelIdentity_r16_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_FailedLogicalChannelIdentity_r16_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FailedLogicalChannelIdentity_r16_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cellGroupIndication-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* logicalChannelIdentity-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* logicalChannelIdentityExt-r16 */
};
asn_SEQUENCE_specifics_t asn_SPC_FailedLogicalChannelIdentity_r16_specs_1 = {
	sizeof(struct FailedLogicalChannelIdentity_r16),
	offsetof(struct FailedLogicalChannelIdentity_r16, _asn_ctx),
	asn_MAP_FailedLogicalChannelIdentity_r16_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_FailedLogicalChannelIdentity_r16_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_FailedLogicalChannelIdentity_r16 = {
	"FailedLogicalChannelIdentity-r16",
	"FailedLogicalChannelIdentity-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_FailedLogicalChannelIdentity_r16_tags_1,
	sizeof(asn_DEF_FailedLogicalChannelIdentity_r16_tags_1)
		/sizeof(asn_DEF_FailedLogicalChannelIdentity_r16_tags_1[0]), /* 1 */
	asn_DEF_FailedLogicalChannelIdentity_r16_tags_1,	/* Same as above */
	sizeof(asn_DEF_FailedLogicalChannelIdentity_r16_tags_1)
		/sizeof(asn_DEF_FailedLogicalChannelIdentity_r16_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_FailedLogicalChannelIdentity_r16_1,
	3,	/* Elements count */
	&asn_SPC_FailedLogicalChannelIdentity_r16_specs_1	/* Additional specs */
};

