/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#include "GNSS-ValidityDuration-r17.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_GNSS_ValidityDuration_r17_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_GNSS_ValidityDuration_r17_value2enum_1[] = {
	{ 0,	3,	"s10" },
	{ 1,	3,	"s20" },
	{ 2,	3,	"s30" },
	{ 3,	3,	"s40" },
	{ 4,	3,	"s50" },
	{ 5,	3,	"s60" },
	{ 6,	4,	"min5" },
	{ 7,	5,	"min10" },
	{ 8,	5,	"min15" },
	{ 9,	5,	"min20" },
	{ 10,	5,	"min25" },
	{ 11,	5,	"min30" },
	{ 12,	5,	"min50" },
	{ 13,	5,	"min90" },
	{ 14,	6,	"min120" },
	{ 15,	8,	"infinity" }
};
static const unsigned int asn_MAP_GNSS_ValidityDuration_r17_enum2value_1[] = {
	15,	/* infinity(15) */
	7,	/* min10(7) */
	14,	/* min120(14) */
	8,	/* min15(8) */
	9,	/* min20(9) */
	10,	/* min25(10) */
	11,	/* min30(11) */
	6,	/* min5(6) */
	12,	/* min50(12) */
	13,	/* min90(13) */
	0,	/* s10(0) */
	1,	/* s20(1) */
	2,	/* s30(2) */
	3,	/* s40(3) */
	4,	/* s50(4) */
	5	/* s60(5) */
};
const asn_INTEGER_specifics_t asn_SPC_GNSS_ValidityDuration_r17_specs_1 = {
	asn_MAP_GNSS_ValidityDuration_r17_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_GNSS_ValidityDuration_r17_enum2value_1,	/* N => "tag"; sorted by N */
	16,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_GNSS_ValidityDuration_r17_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_GNSS_ValidityDuration_r17 = {
	"GNSS-ValidityDuration-r17",
	"GNSS-ValidityDuration-r17",
	&asn_OP_NativeEnumerated,
	asn_DEF_GNSS_ValidityDuration_r17_tags_1,
	sizeof(asn_DEF_GNSS_ValidityDuration_r17_tags_1)
		/sizeof(asn_DEF_GNSS_ValidityDuration_r17_tags_1[0]), /* 1 */
	asn_DEF_GNSS_ValidityDuration_r17_tags_1,	/* Same as above */
	sizeof(asn_DEF_GNSS_ValidityDuration_r17_tags_1)
		/sizeof(asn_DEF_GNSS_ValidityDuration_r17_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_GNSS_ValidityDuration_r17_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_GNSS_ValidityDuration_r17_specs_1	/* Additional specs */
};

