/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_MBMS_SupportedBandInfo_r16_H_
#define	_MBMS_SupportedBandInfo_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MBMS_SupportedBandInfo_r16__subcarrierSpacingMBMS_khz2dot5_r16 {
	MBMS_SupportedBandInfo_r16__subcarrierSpacingMBMS_khz2dot5_r16_supported	= 0
} e_MBMS_SupportedBandInfo_r16__subcarrierSpacingMBMS_khz2dot5_r16;
typedef enum MBMS_SupportedBandInfo_r16__subcarrierSpacingMBMS_khz0dot37_r16__timeSeparationSlot2_r16 {
	MBMS_SupportedBandInfo_r16__subcarrierSpacingMBMS_khz0dot37_r16__timeSeparationSlot2_r16_supported	= 0
} e_MBMS_SupportedBandInfo_r16__subcarrierSpacingMBMS_khz0dot37_r16__timeSeparationSlot2_r16;
typedef enum MBMS_SupportedBandInfo_r16__subcarrierSpacingMBMS_khz0dot37_r16__timeSeparationSlot4_r16 {
	MBMS_SupportedBandInfo_r16__subcarrierSpacingMBMS_khz0dot37_r16__timeSeparationSlot4_r16_supported	= 0
} e_MBMS_SupportedBandInfo_r16__subcarrierSpacingMBMS_khz0dot37_r16__timeSeparationSlot4_r16;

/* MBMS-SupportedBandInfo-r16 */
typedef struct MBMS_SupportedBandInfo_r16 {
	long	*subcarrierSpacingMBMS_khz2dot5_r16;	/* OPTIONAL */
	struct MBMS_SupportedBandInfo_r16__subcarrierSpacingMBMS_khz0dot37_r16 {
		long	*timeSeparationSlot2_r16;	/* OPTIONAL */
		long	*timeSeparationSlot4_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *subcarrierSpacingMBMS_khz0dot37_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBMS_SupportedBandInfo_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_subcarrierSpacingMBMS_khz2dot5_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_timeSeparationSlot2_r16_5;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_timeSeparationSlot4_r16_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MBMS_SupportedBandInfo_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_MBMS_SupportedBandInfo_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_MBMS_SupportedBandInfo_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _MBMS_SupportedBandInfo_r16_H_ */
#include <asn_internal.h>
