/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_MeasRSS_DedicatedConfig_r16_H_
#define	_MeasRSS_DedicatedConfig_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RSS_ConfigCarrierInfo_r16;
struct CellsToAddModList_v1610;

/* MeasRSS-DedicatedConfig-r16 */
typedef struct MeasRSS_DedicatedConfig_r16 {
	struct RSS_ConfigCarrierInfo_r16	*rss_ConfigCarrierInfo_r16;	/* OPTIONAL */
	struct CellsToAddModList_v1610	*cellsToAddModList_v1610;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasRSS_DedicatedConfig_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasRSS_DedicatedConfig_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasRSS_DedicatedConfig_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasRSS_DedicatedConfig_r16_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasRSS_DedicatedConfig_r16_H_ */
#include <asn_internal.h>
