/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_PDCP_ParametersNR_r15_H_
#define	_PDCP_ParametersNR_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ROHC-ProfileSupportList-r15.h"
#include <NativeEnumerated.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15 {
	PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15_cs2	= 0,
	PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15_cs4	= 1,
	PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15_cs8	= 2,
	PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15_cs12	= 3,
	PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15_cs16	= 4,
	PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15_cs24	= 5,
	PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15_cs32	= 6,
	PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15_cs48	= 7,
	PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15_cs64	= 8,
	PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15_cs128	= 9,
	PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15_cs256	= 10,
	PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15_cs512	= 11,
	PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15_cs1024	= 12,
	PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15_cs16384	= 13,
	PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15_spare2	= 14,
	PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15_spare1	= 15
} e_PDCP_ParametersNR_r15__rohc_ContextMaxSessions_r15;
typedef enum PDCP_ParametersNR_r15__rohc_ContextContinue_r15 {
	PDCP_ParametersNR_r15__rohc_ContextContinue_r15_supported	= 0
} e_PDCP_ParametersNR_r15__rohc_ContextContinue_r15;
typedef enum PDCP_ParametersNR_r15__outOfOrderDelivery_r15 {
	PDCP_ParametersNR_r15__outOfOrderDelivery_r15_supported	= 0
} e_PDCP_ParametersNR_r15__outOfOrderDelivery_r15;
typedef enum PDCP_ParametersNR_r15__sn_SizeLo_r15 {
	PDCP_ParametersNR_r15__sn_SizeLo_r15_supported	= 0
} e_PDCP_ParametersNR_r15__sn_SizeLo_r15;
typedef enum PDCP_ParametersNR_r15__ims_VoiceOverNR_PDCP_MCG_Bearer_r15 {
	PDCP_ParametersNR_r15__ims_VoiceOverNR_PDCP_MCG_Bearer_r15_supported	= 0
} e_PDCP_ParametersNR_r15__ims_VoiceOverNR_PDCP_MCG_Bearer_r15;
typedef enum PDCP_ParametersNR_r15__ims_VoiceOverNR_PDCP_SCG_Bearer_r15 {
	PDCP_ParametersNR_r15__ims_VoiceOverNR_PDCP_SCG_Bearer_r15_supported	= 0
} e_PDCP_ParametersNR_r15__ims_VoiceOverNR_PDCP_SCG_Bearer_r15;

/* PDCP-ParametersNR-r15 */
typedef struct PDCP_ParametersNR_r15 {
	ROHC_ProfileSupportList_r15_t	 rohc_Profiles_r15;
	long	*rohc_ContextMaxSessions_r15;	/* DEFAULT 4 */
	struct PDCP_ParametersNR_r15__rohc_ProfilesUL_Only_r15 {
		BOOLEAN_t	 profile0x0006_r15;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} rohc_ProfilesUL_Only_r15;
	long	*rohc_ContextContinue_r15;	/* OPTIONAL */
	long	*outOfOrderDelivery_r15;	/* OPTIONAL */
	long	*sn_SizeLo_r15;	/* OPTIONAL */
	long	*ims_VoiceOverNR_PDCP_MCG_Bearer_r15;	/* OPTIONAL */
	long	*ims_VoiceOverNR_PDCP_SCG_Bearer_r15;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDCP_ParametersNR_r15_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_rohc_ContextMaxSessions_r15_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_rohc_ContextContinue_r15_22;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_outOfOrderDelivery_r15_24;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_sn_SizeLo_r15_26;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ims_VoiceOverNR_PDCP_MCG_Bearer_r15_28;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ims_VoiceOverNR_PDCP_SCG_Bearer_r15_30;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PDCP_ParametersNR_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_PDCP_ParametersNR_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_PDCP_ParametersNR_r15_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _PDCP_ParametersNR_r15_H_ */
#include <asn_internal.h>
