/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#include "PDSCH-ConfigDedicated-v1700.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_ce_PDSCH_14HARQ_Config_r17_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_ce_PDSCH_maxTBS_r17_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_ce_PDSCH_14HARQ_Config_r17_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PDSCH_ConfigDedicated_v1700__ce_PDSCH_14HARQ_Config_r17, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDSCH_ConfigDedicated_v1700__ce_PDSCH_14HARQ_Config_r17, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CE_PDSCH_14HARQ_Config_r17,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"setup"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ce_PDSCH_14HARQ_Config_r17_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_ce_PDSCH_14HARQ_Config_r17_specs_2 = {
	sizeof(struct PDSCH_ConfigDedicated_v1700__ce_PDSCH_14HARQ_Config_r17),
	offsetof(struct PDSCH_ConfigDedicated_v1700__ce_PDSCH_14HARQ_Config_r17, _asn_ctx),
	offsetof(struct PDSCH_ConfigDedicated_v1700__ce_PDSCH_14HARQ_Config_r17, present),
	sizeof(((struct PDSCH_ConfigDedicated_v1700__ce_PDSCH_14HARQ_Config_r17 *)0)->present),
	asn_MAP_ce_PDSCH_14HARQ_Config_r17_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ce_PDSCH_14HARQ_Config_r17_2 = {
	"ce-PDSCH-14HARQ-Config-r17",
	"ce-PDSCH-14HARQ-Config-r17",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ce_PDSCH_14HARQ_Config_r17_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_ce_PDSCH_14HARQ_Config_r17_2,
	2,	/* Elements count */
	&asn_SPC_ce_PDSCH_14HARQ_Config_r17_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ce_PDSCH_maxTBS_r17_value2enum_5[] = {
	{ 0,	7,	"enabled" }
};
static const unsigned int asn_MAP_ce_PDSCH_maxTBS_r17_enum2value_5[] = {
	0	/* enabled(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ce_PDSCH_maxTBS_r17_specs_5 = {
	asn_MAP_ce_PDSCH_maxTBS_r17_value2enum_5,	/* "tag" => N; sorted by tag */
	asn_MAP_ce_PDSCH_maxTBS_r17_enum2value_5,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ce_PDSCH_maxTBS_r17_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ce_PDSCH_maxTBS_r17_5 = {
	"ce-PDSCH-maxTBS-r17",
	"ce-PDSCH-maxTBS-r17",
	&asn_OP_NativeEnumerated,
	asn_DEF_ce_PDSCH_maxTBS_r17_tags_5,
	sizeof(asn_DEF_ce_PDSCH_maxTBS_r17_tags_5)
		/sizeof(asn_DEF_ce_PDSCH_maxTBS_r17_tags_5[0]) - 1, /* 1 */
	asn_DEF_ce_PDSCH_maxTBS_r17_tags_5,	/* Same as above */
	sizeof(asn_DEF_ce_PDSCH_maxTBS_r17_tags_5)
		/sizeof(asn_DEF_ce_PDSCH_maxTBS_r17_tags_5[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ce_PDSCH_maxTBS_r17_constr_5,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ce_PDSCH_maxTBS_r17_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PDSCH_ConfigDedicated_v1700_1[] = {
	{ ATF_POINTER, 2, offsetof(struct PDSCH_ConfigDedicated_v1700, ce_PDSCH_14HARQ_Config_r17),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ce_PDSCH_14HARQ_Config_r17_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ce-PDSCH-14HARQ-Config-r17"
		},
	{ ATF_POINTER, 1, offsetof(struct PDSCH_ConfigDedicated_v1700, ce_PDSCH_maxTBS_r17),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ce_PDSCH_maxTBS_r17_5,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ce-PDSCH-maxTBS-r17"
		},
};
static const int asn_MAP_PDSCH_ConfigDedicated_v1700_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_PDSCH_ConfigDedicated_v1700_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PDSCH_ConfigDedicated_v1700_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ce-PDSCH-14HARQ-Config-r17 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ce-PDSCH-maxTBS-r17 */
};
asn_SEQUENCE_specifics_t asn_SPC_PDSCH_ConfigDedicated_v1700_specs_1 = {
	sizeof(struct PDSCH_ConfigDedicated_v1700),
	offsetof(struct PDSCH_ConfigDedicated_v1700, _asn_ctx),
	asn_MAP_PDSCH_ConfigDedicated_v1700_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_PDSCH_ConfigDedicated_v1700_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PDSCH_ConfigDedicated_v1700 = {
	"PDSCH-ConfigDedicated-v1700",
	"PDSCH-ConfigDedicated-v1700",
	&asn_OP_SEQUENCE,
	asn_DEF_PDSCH_ConfigDedicated_v1700_tags_1,
	sizeof(asn_DEF_PDSCH_ConfigDedicated_v1700_tags_1)
		/sizeof(asn_DEF_PDSCH_ConfigDedicated_v1700_tags_1[0]), /* 1 */
	asn_DEF_PDSCH_ConfigDedicated_v1700_tags_1,	/* Same as above */
	sizeof(asn_DEF_PDSCH_ConfigDedicated_v1700_tags_1)
		/sizeof(asn_DEF_PDSCH_ConfigDedicated_v1700_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_PDSCH_ConfigDedicated_v1700_1,
	2,	/* Elements count */
	&asn_SPC_PDSCH_ConfigDedicated_v1700_specs_1	/* Additional specs */
};

