/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#include "PhyLayerParameters-v1610.h"

#include "CE-MultiTB-Parameters-r16.h"
#include "CE-ResourceResvParameters-r16.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_ce_CSI_RS_Feedback_r16_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_ce_CSI_RS_FeedbackCodebookRestriction_r16_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_crs_ChEstMPDCCH_CE_ModeA_r16_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_crs_ChEstMPDCCH_CE_ModeB_r16_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_crs_ChEstMPDCCH_CSI_r16_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_crs_ChEstMPDCCH_ReciprocityTDD_r16_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_etws_CMAS_RxInConnCE_ModeA_r16_constr_15 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_etws_CMAS_RxInConnCE_ModeB_r16_constr_17 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_mpdcch_InLteControlRegionCE_ModeA_r16_constr_19 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_mpdcch_InLteControlRegionCE_ModeB_r16_constr_21 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_pdsch_InLteControlRegionCE_ModeA_r16_constr_23 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_pdsch_InLteControlRegionCE_ModeB_r16_constr_25 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_widebandPRG_Slot_r16_constr_29 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_widebandPRG_Subslot_r16_constr_31 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_widebandPRG_Subframe_r16_constr_33 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_addSRS_FrequencyHopping_r16_constr_36 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_addSRS_AntennaSwitching_r16_constr_38 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_addSRS_CarrierSwitching_r16_constr_40 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_virtualCellID_BasicSRS_r16_constr_42 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_virtualCellID_AddSRS_r16_constr_44 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_ce_CSI_RS_Feedback_r16_value2enum_3[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ce_CSI_RS_Feedback_r16_enum2value_3[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ce_CSI_RS_Feedback_r16_specs_3 = {
	asn_MAP_ce_CSI_RS_Feedback_r16_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_ce_CSI_RS_Feedback_r16_enum2value_3,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ce_CSI_RS_Feedback_r16_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ce_CSI_RS_Feedback_r16_3 = {
	"ce-CSI-RS-Feedback-r16",
	"ce-CSI-RS-Feedback-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_ce_CSI_RS_Feedback_r16_tags_3,
	sizeof(asn_DEF_ce_CSI_RS_Feedback_r16_tags_3)
		/sizeof(asn_DEF_ce_CSI_RS_Feedback_r16_tags_3[0]) - 1, /* 1 */
	asn_DEF_ce_CSI_RS_Feedback_r16_tags_3,	/* Same as above */
	sizeof(asn_DEF_ce_CSI_RS_Feedback_r16_tags_3)
		/sizeof(asn_DEF_ce_CSI_RS_Feedback_r16_tags_3[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ce_CSI_RS_Feedback_r16_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ce_CSI_RS_Feedback_r16_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ce_CSI_RS_FeedbackCodebookRestriction_r16_value2enum_5[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_ce_CSI_RS_FeedbackCodebookRestriction_r16_enum2value_5[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_ce_CSI_RS_FeedbackCodebookRestriction_r16_specs_5 = {
	asn_MAP_ce_CSI_RS_FeedbackCodebookRestriction_r16_value2enum_5,	/* "tag" => N; sorted by tag */
	asn_MAP_ce_CSI_RS_FeedbackCodebookRestriction_r16_enum2value_5,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ce_CSI_RS_FeedbackCodebookRestriction_r16_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ce_CSI_RS_FeedbackCodebookRestriction_r16_5 = {
	"ce-CSI-RS-FeedbackCodebookRestriction-r16",
	"ce-CSI-RS-FeedbackCodebookRestriction-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_ce_CSI_RS_FeedbackCodebookRestriction_r16_tags_5,
	sizeof(asn_DEF_ce_CSI_RS_FeedbackCodebookRestriction_r16_tags_5)
		/sizeof(asn_DEF_ce_CSI_RS_FeedbackCodebookRestriction_r16_tags_5[0]) - 1, /* 1 */
	asn_DEF_ce_CSI_RS_FeedbackCodebookRestriction_r16_tags_5,	/* Same as above */
	sizeof(asn_DEF_ce_CSI_RS_FeedbackCodebookRestriction_r16_tags_5)
		/sizeof(asn_DEF_ce_CSI_RS_FeedbackCodebookRestriction_r16_tags_5[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ce_CSI_RS_FeedbackCodebookRestriction_r16_constr_5,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ce_CSI_RS_FeedbackCodebookRestriction_r16_specs_5	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_crs_ChEstMPDCCH_CE_ModeA_r16_value2enum_7[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_crs_ChEstMPDCCH_CE_ModeA_r16_enum2value_7[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_crs_ChEstMPDCCH_CE_ModeA_r16_specs_7 = {
	asn_MAP_crs_ChEstMPDCCH_CE_ModeA_r16_value2enum_7,	/* "tag" => N; sorted by tag */
	asn_MAP_crs_ChEstMPDCCH_CE_ModeA_r16_enum2value_7,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_crs_ChEstMPDCCH_CE_ModeA_r16_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_crs_ChEstMPDCCH_CE_ModeA_r16_7 = {
	"crs-ChEstMPDCCH-CE-ModeA-r16",
	"crs-ChEstMPDCCH-CE-ModeA-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_crs_ChEstMPDCCH_CE_ModeA_r16_tags_7,
	sizeof(asn_DEF_crs_ChEstMPDCCH_CE_ModeA_r16_tags_7)
		/sizeof(asn_DEF_crs_ChEstMPDCCH_CE_ModeA_r16_tags_7[0]) - 1, /* 1 */
	asn_DEF_crs_ChEstMPDCCH_CE_ModeA_r16_tags_7,	/* Same as above */
	sizeof(asn_DEF_crs_ChEstMPDCCH_CE_ModeA_r16_tags_7)
		/sizeof(asn_DEF_crs_ChEstMPDCCH_CE_ModeA_r16_tags_7[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_crs_ChEstMPDCCH_CE_ModeA_r16_constr_7,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_crs_ChEstMPDCCH_CE_ModeA_r16_specs_7	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_crs_ChEstMPDCCH_CE_ModeB_r16_value2enum_9[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_crs_ChEstMPDCCH_CE_ModeB_r16_enum2value_9[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_crs_ChEstMPDCCH_CE_ModeB_r16_specs_9 = {
	asn_MAP_crs_ChEstMPDCCH_CE_ModeB_r16_value2enum_9,	/* "tag" => N; sorted by tag */
	asn_MAP_crs_ChEstMPDCCH_CE_ModeB_r16_enum2value_9,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_crs_ChEstMPDCCH_CE_ModeB_r16_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_crs_ChEstMPDCCH_CE_ModeB_r16_9 = {
	"crs-ChEstMPDCCH-CE-ModeB-r16",
	"crs-ChEstMPDCCH-CE-ModeB-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_crs_ChEstMPDCCH_CE_ModeB_r16_tags_9,
	sizeof(asn_DEF_crs_ChEstMPDCCH_CE_ModeB_r16_tags_9)
		/sizeof(asn_DEF_crs_ChEstMPDCCH_CE_ModeB_r16_tags_9[0]) - 1, /* 1 */
	asn_DEF_crs_ChEstMPDCCH_CE_ModeB_r16_tags_9,	/* Same as above */
	sizeof(asn_DEF_crs_ChEstMPDCCH_CE_ModeB_r16_tags_9)
		/sizeof(asn_DEF_crs_ChEstMPDCCH_CE_ModeB_r16_tags_9[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_crs_ChEstMPDCCH_CE_ModeB_r16_constr_9,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_crs_ChEstMPDCCH_CE_ModeB_r16_specs_9	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_crs_ChEstMPDCCH_CSI_r16_value2enum_11[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_crs_ChEstMPDCCH_CSI_r16_enum2value_11[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_crs_ChEstMPDCCH_CSI_r16_specs_11 = {
	asn_MAP_crs_ChEstMPDCCH_CSI_r16_value2enum_11,	/* "tag" => N; sorted by tag */
	asn_MAP_crs_ChEstMPDCCH_CSI_r16_enum2value_11,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_crs_ChEstMPDCCH_CSI_r16_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_crs_ChEstMPDCCH_CSI_r16_11 = {
	"crs-ChEstMPDCCH-CSI-r16",
	"crs-ChEstMPDCCH-CSI-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_crs_ChEstMPDCCH_CSI_r16_tags_11,
	sizeof(asn_DEF_crs_ChEstMPDCCH_CSI_r16_tags_11)
		/sizeof(asn_DEF_crs_ChEstMPDCCH_CSI_r16_tags_11[0]) - 1, /* 1 */
	asn_DEF_crs_ChEstMPDCCH_CSI_r16_tags_11,	/* Same as above */
	sizeof(asn_DEF_crs_ChEstMPDCCH_CSI_r16_tags_11)
		/sizeof(asn_DEF_crs_ChEstMPDCCH_CSI_r16_tags_11[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_crs_ChEstMPDCCH_CSI_r16_constr_11,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_crs_ChEstMPDCCH_CSI_r16_specs_11	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_crs_ChEstMPDCCH_ReciprocityTDD_r16_value2enum_13[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_crs_ChEstMPDCCH_ReciprocityTDD_r16_enum2value_13[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_crs_ChEstMPDCCH_ReciprocityTDD_r16_specs_13 = {
	asn_MAP_crs_ChEstMPDCCH_ReciprocityTDD_r16_value2enum_13,	/* "tag" => N; sorted by tag */
	asn_MAP_crs_ChEstMPDCCH_ReciprocityTDD_r16_enum2value_13,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_crs_ChEstMPDCCH_ReciprocityTDD_r16_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_crs_ChEstMPDCCH_ReciprocityTDD_r16_13 = {
	"crs-ChEstMPDCCH-ReciprocityTDD-r16",
	"crs-ChEstMPDCCH-ReciprocityTDD-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_crs_ChEstMPDCCH_ReciprocityTDD_r16_tags_13,
	sizeof(asn_DEF_crs_ChEstMPDCCH_ReciprocityTDD_r16_tags_13)
		/sizeof(asn_DEF_crs_ChEstMPDCCH_ReciprocityTDD_r16_tags_13[0]) - 1, /* 1 */
	asn_DEF_crs_ChEstMPDCCH_ReciprocityTDD_r16_tags_13,	/* Same as above */
	sizeof(asn_DEF_crs_ChEstMPDCCH_ReciprocityTDD_r16_tags_13)
		/sizeof(asn_DEF_crs_ChEstMPDCCH_ReciprocityTDD_r16_tags_13[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_crs_ChEstMPDCCH_ReciprocityTDD_r16_constr_13,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_crs_ChEstMPDCCH_ReciprocityTDD_r16_specs_13	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_etws_CMAS_RxInConnCE_ModeA_r16_value2enum_15[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_etws_CMAS_RxInConnCE_ModeA_r16_enum2value_15[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_etws_CMAS_RxInConnCE_ModeA_r16_specs_15 = {
	asn_MAP_etws_CMAS_RxInConnCE_ModeA_r16_value2enum_15,	/* "tag" => N; sorted by tag */
	asn_MAP_etws_CMAS_RxInConnCE_ModeA_r16_enum2value_15,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_etws_CMAS_RxInConnCE_ModeA_r16_tags_15[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_etws_CMAS_RxInConnCE_ModeA_r16_15 = {
	"etws-CMAS-RxInConnCE-ModeA-r16",
	"etws-CMAS-RxInConnCE-ModeA-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_etws_CMAS_RxInConnCE_ModeA_r16_tags_15,
	sizeof(asn_DEF_etws_CMAS_RxInConnCE_ModeA_r16_tags_15)
		/sizeof(asn_DEF_etws_CMAS_RxInConnCE_ModeA_r16_tags_15[0]) - 1, /* 1 */
	asn_DEF_etws_CMAS_RxInConnCE_ModeA_r16_tags_15,	/* Same as above */
	sizeof(asn_DEF_etws_CMAS_RxInConnCE_ModeA_r16_tags_15)
		/sizeof(asn_DEF_etws_CMAS_RxInConnCE_ModeA_r16_tags_15[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_etws_CMAS_RxInConnCE_ModeA_r16_constr_15,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_etws_CMAS_RxInConnCE_ModeA_r16_specs_15	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_etws_CMAS_RxInConnCE_ModeB_r16_value2enum_17[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_etws_CMAS_RxInConnCE_ModeB_r16_enum2value_17[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_etws_CMAS_RxInConnCE_ModeB_r16_specs_17 = {
	asn_MAP_etws_CMAS_RxInConnCE_ModeB_r16_value2enum_17,	/* "tag" => N; sorted by tag */
	asn_MAP_etws_CMAS_RxInConnCE_ModeB_r16_enum2value_17,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_etws_CMAS_RxInConnCE_ModeB_r16_tags_17[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_etws_CMAS_RxInConnCE_ModeB_r16_17 = {
	"etws-CMAS-RxInConnCE-ModeB-r16",
	"etws-CMAS-RxInConnCE-ModeB-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_etws_CMAS_RxInConnCE_ModeB_r16_tags_17,
	sizeof(asn_DEF_etws_CMAS_RxInConnCE_ModeB_r16_tags_17)
		/sizeof(asn_DEF_etws_CMAS_RxInConnCE_ModeB_r16_tags_17[0]) - 1, /* 1 */
	asn_DEF_etws_CMAS_RxInConnCE_ModeB_r16_tags_17,	/* Same as above */
	sizeof(asn_DEF_etws_CMAS_RxInConnCE_ModeB_r16_tags_17)
		/sizeof(asn_DEF_etws_CMAS_RxInConnCE_ModeB_r16_tags_17[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_etws_CMAS_RxInConnCE_ModeB_r16_constr_17,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_etws_CMAS_RxInConnCE_ModeB_r16_specs_17	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_mpdcch_InLteControlRegionCE_ModeA_r16_value2enum_19[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_mpdcch_InLteControlRegionCE_ModeA_r16_enum2value_19[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_mpdcch_InLteControlRegionCE_ModeA_r16_specs_19 = {
	asn_MAP_mpdcch_InLteControlRegionCE_ModeA_r16_value2enum_19,	/* "tag" => N; sorted by tag */
	asn_MAP_mpdcch_InLteControlRegionCE_ModeA_r16_enum2value_19,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_mpdcch_InLteControlRegionCE_ModeA_r16_tags_19[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mpdcch_InLteControlRegionCE_ModeA_r16_19 = {
	"mpdcch-InLteControlRegionCE-ModeA-r16",
	"mpdcch-InLteControlRegionCE-ModeA-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_mpdcch_InLteControlRegionCE_ModeA_r16_tags_19,
	sizeof(asn_DEF_mpdcch_InLteControlRegionCE_ModeA_r16_tags_19)
		/sizeof(asn_DEF_mpdcch_InLteControlRegionCE_ModeA_r16_tags_19[0]) - 1, /* 1 */
	asn_DEF_mpdcch_InLteControlRegionCE_ModeA_r16_tags_19,	/* Same as above */
	sizeof(asn_DEF_mpdcch_InLteControlRegionCE_ModeA_r16_tags_19)
		/sizeof(asn_DEF_mpdcch_InLteControlRegionCE_ModeA_r16_tags_19[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_mpdcch_InLteControlRegionCE_ModeA_r16_constr_19,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_mpdcch_InLteControlRegionCE_ModeA_r16_specs_19	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_mpdcch_InLteControlRegionCE_ModeB_r16_value2enum_21[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_mpdcch_InLteControlRegionCE_ModeB_r16_enum2value_21[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_mpdcch_InLteControlRegionCE_ModeB_r16_specs_21 = {
	asn_MAP_mpdcch_InLteControlRegionCE_ModeB_r16_value2enum_21,	/* "tag" => N; sorted by tag */
	asn_MAP_mpdcch_InLteControlRegionCE_ModeB_r16_enum2value_21,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_mpdcch_InLteControlRegionCE_ModeB_r16_tags_21[] = {
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_mpdcch_InLteControlRegionCE_ModeB_r16_21 = {
	"mpdcch-InLteControlRegionCE-ModeB-r16",
	"mpdcch-InLteControlRegionCE-ModeB-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_mpdcch_InLteControlRegionCE_ModeB_r16_tags_21,
	sizeof(asn_DEF_mpdcch_InLteControlRegionCE_ModeB_r16_tags_21)
		/sizeof(asn_DEF_mpdcch_InLteControlRegionCE_ModeB_r16_tags_21[0]) - 1, /* 1 */
	asn_DEF_mpdcch_InLteControlRegionCE_ModeB_r16_tags_21,	/* Same as above */
	sizeof(asn_DEF_mpdcch_InLteControlRegionCE_ModeB_r16_tags_21)
		/sizeof(asn_DEF_mpdcch_InLteControlRegionCE_ModeB_r16_tags_21[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_mpdcch_InLteControlRegionCE_ModeB_r16_constr_21,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_mpdcch_InLteControlRegionCE_ModeB_r16_specs_21	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_pdsch_InLteControlRegionCE_ModeA_r16_value2enum_23[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_pdsch_InLteControlRegionCE_ModeA_r16_enum2value_23[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_pdsch_InLteControlRegionCE_ModeA_r16_specs_23 = {
	asn_MAP_pdsch_InLteControlRegionCE_ModeA_r16_value2enum_23,	/* "tag" => N; sorted by tag */
	asn_MAP_pdsch_InLteControlRegionCE_ModeA_r16_enum2value_23,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_pdsch_InLteControlRegionCE_ModeA_r16_tags_23[] = {
	(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_pdsch_InLteControlRegionCE_ModeA_r16_23 = {
	"pdsch-InLteControlRegionCE-ModeA-r16",
	"pdsch-InLteControlRegionCE-ModeA-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_pdsch_InLteControlRegionCE_ModeA_r16_tags_23,
	sizeof(asn_DEF_pdsch_InLteControlRegionCE_ModeA_r16_tags_23)
		/sizeof(asn_DEF_pdsch_InLteControlRegionCE_ModeA_r16_tags_23[0]) - 1, /* 1 */
	asn_DEF_pdsch_InLteControlRegionCE_ModeA_r16_tags_23,	/* Same as above */
	sizeof(asn_DEF_pdsch_InLteControlRegionCE_ModeA_r16_tags_23)
		/sizeof(asn_DEF_pdsch_InLteControlRegionCE_ModeA_r16_tags_23[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_pdsch_InLteControlRegionCE_ModeA_r16_constr_23,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_pdsch_InLteControlRegionCE_ModeA_r16_specs_23	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_pdsch_InLteControlRegionCE_ModeB_r16_value2enum_25[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_pdsch_InLteControlRegionCE_ModeB_r16_enum2value_25[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_pdsch_InLteControlRegionCE_ModeB_r16_specs_25 = {
	asn_MAP_pdsch_InLteControlRegionCE_ModeB_r16_value2enum_25,	/* "tag" => N; sorted by tag */
	asn_MAP_pdsch_InLteControlRegionCE_ModeB_r16_enum2value_25,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_pdsch_InLteControlRegionCE_ModeB_r16_tags_25[] = {
	(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_pdsch_InLteControlRegionCE_ModeB_r16_25 = {
	"pdsch-InLteControlRegionCE-ModeB-r16",
	"pdsch-InLteControlRegionCE-ModeB-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_pdsch_InLteControlRegionCE_ModeB_r16_tags_25,
	sizeof(asn_DEF_pdsch_InLteControlRegionCE_ModeB_r16_tags_25)
		/sizeof(asn_DEF_pdsch_InLteControlRegionCE_ModeB_r16_tags_25[0]) - 1, /* 1 */
	asn_DEF_pdsch_InLteControlRegionCE_ModeB_r16_tags_25,	/* Same as above */
	sizeof(asn_DEF_pdsch_InLteControlRegionCE_ModeB_r16_tags_25)
		/sizeof(asn_DEF_pdsch_InLteControlRegionCE_ModeB_r16_tags_25[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_pdsch_InLteControlRegionCE_ModeB_r16_constr_25,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_pdsch_InLteControlRegionCE_ModeB_r16_specs_25	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ce_Capabilities_v1610_2[] = {
	{ ATF_POINTER, 14, offsetof(struct PhyLayerParameters_v1610__ce_Capabilities_v1610, ce_CSI_RS_Feedback_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ce_CSI_RS_Feedback_r16_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ce-CSI-RS-Feedback-r16"
		},
	{ ATF_POINTER, 13, offsetof(struct PhyLayerParameters_v1610__ce_Capabilities_v1610, ce_CSI_RS_FeedbackCodebookRestriction_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ce_CSI_RS_FeedbackCodebookRestriction_r16_5,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ce-CSI-RS-FeedbackCodebookRestriction-r16"
		},
	{ ATF_POINTER, 12, offsetof(struct PhyLayerParameters_v1610__ce_Capabilities_v1610, crs_ChEstMPDCCH_CE_ModeA_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_crs_ChEstMPDCCH_CE_ModeA_r16_7,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"crs-ChEstMPDCCH-CE-ModeA-r16"
		},
	{ ATF_POINTER, 11, offsetof(struct PhyLayerParameters_v1610__ce_Capabilities_v1610, crs_ChEstMPDCCH_CE_ModeB_r16),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_crs_ChEstMPDCCH_CE_ModeB_r16_9,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"crs-ChEstMPDCCH-CE-ModeB-r16"
		},
	{ ATF_POINTER, 10, offsetof(struct PhyLayerParameters_v1610__ce_Capabilities_v1610, crs_ChEstMPDCCH_CSI_r16),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_crs_ChEstMPDCCH_CSI_r16_11,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"crs-ChEstMPDCCH-CSI-r16"
		},
	{ ATF_POINTER, 9, offsetof(struct PhyLayerParameters_v1610__ce_Capabilities_v1610, crs_ChEstMPDCCH_ReciprocityTDD_r16),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_crs_ChEstMPDCCH_ReciprocityTDD_r16_13,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"crs-ChEstMPDCCH-ReciprocityTDD-r16"
		},
	{ ATF_POINTER, 8, offsetof(struct PhyLayerParameters_v1610__ce_Capabilities_v1610, etws_CMAS_RxInConnCE_ModeA_r16),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_etws_CMAS_RxInConnCE_ModeA_r16_15,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"etws-CMAS-RxInConnCE-ModeA-r16"
		},
	{ ATF_POINTER, 7, offsetof(struct PhyLayerParameters_v1610__ce_Capabilities_v1610, etws_CMAS_RxInConnCE_ModeB_r16),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_etws_CMAS_RxInConnCE_ModeB_r16_17,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"etws-CMAS-RxInConnCE-ModeB-r16"
		},
	{ ATF_POINTER, 6, offsetof(struct PhyLayerParameters_v1610__ce_Capabilities_v1610, mpdcch_InLteControlRegionCE_ModeA_r16),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_mpdcch_InLteControlRegionCE_ModeA_r16_19,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"mpdcch-InLteControlRegionCE-ModeA-r16"
		},
	{ ATF_POINTER, 5, offsetof(struct PhyLayerParameters_v1610__ce_Capabilities_v1610, mpdcch_InLteControlRegionCE_ModeB_r16),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_mpdcch_InLteControlRegionCE_ModeB_r16_21,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"mpdcch-InLteControlRegionCE-ModeB-r16"
		},
	{ ATF_POINTER, 4, offsetof(struct PhyLayerParameters_v1610__ce_Capabilities_v1610, pdsch_InLteControlRegionCE_ModeA_r16),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_pdsch_InLteControlRegionCE_ModeA_r16_23,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"pdsch-InLteControlRegionCE-ModeA-r16"
		},
	{ ATF_POINTER, 3, offsetof(struct PhyLayerParameters_v1610__ce_Capabilities_v1610, pdsch_InLteControlRegionCE_ModeB_r16),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_pdsch_InLteControlRegionCE_ModeB_r16_25,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"pdsch-InLteControlRegionCE-ModeB-r16"
		},
	{ ATF_POINTER, 2, offsetof(struct PhyLayerParameters_v1610__ce_Capabilities_v1610, multiTB_Parameters_r16),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CE_MultiTB_Parameters_r16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"multiTB-Parameters-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct PhyLayerParameters_v1610__ce_Capabilities_v1610, resourceResvParameters_r16),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CE_ResourceResvParameters_r16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"resourceResvParameters-r16"
		},
};
static const int asn_MAP_ce_Capabilities_v1610_oms_2[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 };
static const ber_tlv_tag_t asn_DEF_ce_Capabilities_v1610_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ce_Capabilities_v1610_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ce-CSI-RS-Feedback-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ce-CSI-RS-FeedbackCodebookRestriction-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* crs-ChEstMPDCCH-CE-ModeA-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* crs-ChEstMPDCCH-CE-ModeB-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* crs-ChEstMPDCCH-CSI-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* crs-ChEstMPDCCH-ReciprocityTDD-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* etws-CMAS-RxInConnCE-ModeA-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* etws-CMAS-RxInConnCE-ModeB-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* mpdcch-InLteControlRegionCE-ModeA-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* mpdcch-InLteControlRegionCE-ModeB-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* pdsch-InLteControlRegionCE-ModeA-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* pdsch-InLteControlRegionCE-ModeB-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* multiTB-Parameters-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 } /* resourceResvParameters-r16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ce_Capabilities_v1610_specs_2 = {
	sizeof(struct PhyLayerParameters_v1610__ce_Capabilities_v1610),
	offsetof(struct PhyLayerParameters_v1610__ce_Capabilities_v1610, _asn_ctx),
	asn_MAP_ce_Capabilities_v1610_tag2el_2,
	14,	/* Count of tags in the map */
	asn_MAP_ce_Capabilities_v1610_oms_2,	/* Optional members */
	14, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ce_Capabilities_v1610_2 = {
	"ce-Capabilities-v1610",
	"ce-Capabilities-v1610",
	&asn_OP_SEQUENCE,
	asn_DEF_ce_Capabilities_v1610_tags_2,
	sizeof(asn_DEF_ce_Capabilities_v1610_tags_2)
		/sizeof(asn_DEF_ce_Capabilities_v1610_tags_2[0]) - 1, /* 1 */
	asn_DEF_ce_Capabilities_v1610_tags_2,	/* Same as above */
	sizeof(asn_DEF_ce_Capabilities_v1610_tags_2)
		/sizeof(asn_DEF_ce_Capabilities_v1610_tags_2[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ce_Capabilities_v1610_2,
	14,	/* Elements count */
	&asn_SPC_ce_Capabilities_v1610_specs_2	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_widebandPRG_Slot_r16_value2enum_29[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_widebandPRG_Slot_r16_enum2value_29[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_widebandPRG_Slot_r16_specs_29 = {
	asn_MAP_widebandPRG_Slot_r16_value2enum_29,	/* "tag" => N; sorted by tag */
	asn_MAP_widebandPRG_Slot_r16_enum2value_29,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_widebandPRG_Slot_r16_tags_29[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_widebandPRG_Slot_r16_29 = {
	"widebandPRG-Slot-r16",
	"widebandPRG-Slot-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_widebandPRG_Slot_r16_tags_29,
	sizeof(asn_DEF_widebandPRG_Slot_r16_tags_29)
		/sizeof(asn_DEF_widebandPRG_Slot_r16_tags_29[0]) - 1, /* 1 */
	asn_DEF_widebandPRG_Slot_r16_tags_29,	/* Same as above */
	sizeof(asn_DEF_widebandPRG_Slot_r16_tags_29)
		/sizeof(asn_DEF_widebandPRG_Slot_r16_tags_29[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_widebandPRG_Slot_r16_constr_29,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_widebandPRG_Slot_r16_specs_29	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_widebandPRG_Subslot_r16_value2enum_31[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_widebandPRG_Subslot_r16_enum2value_31[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_widebandPRG_Subslot_r16_specs_31 = {
	asn_MAP_widebandPRG_Subslot_r16_value2enum_31,	/* "tag" => N; sorted by tag */
	asn_MAP_widebandPRG_Subslot_r16_enum2value_31,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_widebandPRG_Subslot_r16_tags_31[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_widebandPRG_Subslot_r16_31 = {
	"widebandPRG-Subslot-r16",
	"widebandPRG-Subslot-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_widebandPRG_Subslot_r16_tags_31,
	sizeof(asn_DEF_widebandPRG_Subslot_r16_tags_31)
		/sizeof(asn_DEF_widebandPRG_Subslot_r16_tags_31[0]) - 1, /* 1 */
	asn_DEF_widebandPRG_Subslot_r16_tags_31,	/* Same as above */
	sizeof(asn_DEF_widebandPRG_Subslot_r16_tags_31)
		/sizeof(asn_DEF_widebandPRG_Subslot_r16_tags_31[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_widebandPRG_Subslot_r16_constr_31,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_widebandPRG_Subslot_r16_specs_31	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_widebandPRG_Subframe_r16_value2enum_33[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_widebandPRG_Subframe_r16_enum2value_33[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_widebandPRG_Subframe_r16_specs_33 = {
	asn_MAP_widebandPRG_Subframe_r16_value2enum_33,	/* "tag" => N; sorted by tag */
	asn_MAP_widebandPRG_Subframe_r16_enum2value_33,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_widebandPRG_Subframe_r16_tags_33[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_widebandPRG_Subframe_r16_33 = {
	"widebandPRG-Subframe-r16",
	"widebandPRG-Subframe-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_widebandPRG_Subframe_r16_tags_33,
	sizeof(asn_DEF_widebandPRG_Subframe_r16_tags_33)
		/sizeof(asn_DEF_widebandPRG_Subframe_r16_tags_33[0]) - 1, /* 1 */
	asn_DEF_widebandPRG_Subframe_r16_tags_33,	/* Same as above */
	sizeof(asn_DEF_widebandPRG_Subframe_r16_tags_33)
		/sizeof(asn_DEF_widebandPRG_Subframe_r16_tags_33[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_widebandPRG_Subframe_r16_constr_33,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_widebandPRG_Subframe_r16_specs_33	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_addSRS_FrequencyHopping_r16_value2enum_36[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_addSRS_FrequencyHopping_r16_enum2value_36[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_addSRS_FrequencyHopping_r16_specs_36 = {
	asn_MAP_addSRS_FrequencyHopping_r16_value2enum_36,	/* "tag" => N; sorted by tag */
	asn_MAP_addSRS_FrequencyHopping_r16_enum2value_36,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_addSRS_FrequencyHopping_r16_tags_36[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_addSRS_FrequencyHopping_r16_36 = {
	"addSRS-FrequencyHopping-r16",
	"addSRS-FrequencyHopping-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_addSRS_FrequencyHopping_r16_tags_36,
	sizeof(asn_DEF_addSRS_FrequencyHopping_r16_tags_36)
		/sizeof(asn_DEF_addSRS_FrequencyHopping_r16_tags_36[0]) - 1, /* 1 */
	asn_DEF_addSRS_FrequencyHopping_r16_tags_36,	/* Same as above */
	sizeof(asn_DEF_addSRS_FrequencyHopping_r16_tags_36)
		/sizeof(asn_DEF_addSRS_FrequencyHopping_r16_tags_36[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_addSRS_FrequencyHopping_r16_constr_36,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_addSRS_FrequencyHopping_r16_specs_36	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_addSRS_AntennaSwitching_r16_value2enum_38[] = {
	{ 0,	8,	"useBasic" }
};
static const unsigned int asn_MAP_addSRS_AntennaSwitching_r16_enum2value_38[] = {
	0	/* useBasic(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_addSRS_AntennaSwitching_r16_specs_38 = {
	asn_MAP_addSRS_AntennaSwitching_r16_value2enum_38,	/* "tag" => N; sorted by tag */
	asn_MAP_addSRS_AntennaSwitching_r16_enum2value_38,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_addSRS_AntennaSwitching_r16_tags_38[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_addSRS_AntennaSwitching_r16_38 = {
	"addSRS-AntennaSwitching-r16",
	"addSRS-AntennaSwitching-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_addSRS_AntennaSwitching_r16_tags_38,
	sizeof(asn_DEF_addSRS_AntennaSwitching_r16_tags_38)
		/sizeof(asn_DEF_addSRS_AntennaSwitching_r16_tags_38[0]) - 1, /* 1 */
	asn_DEF_addSRS_AntennaSwitching_r16_tags_38,	/* Same as above */
	sizeof(asn_DEF_addSRS_AntennaSwitching_r16_tags_38)
		/sizeof(asn_DEF_addSRS_AntennaSwitching_r16_tags_38[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_addSRS_AntennaSwitching_r16_constr_38,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_addSRS_AntennaSwitching_r16_specs_38	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_addSRS_CarrierSwitching_r16_value2enum_40[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_addSRS_CarrierSwitching_r16_enum2value_40[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_addSRS_CarrierSwitching_r16_specs_40 = {
	asn_MAP_addSRS_CarrierSwitching_r16_value2enum_40,	/* "tag" => N; sorted by tag */
	asn_MAP_addSRS_CarrierSwitching_r16_enum2value_40,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_addSRS_CarrierSwitching_r16_tags_40[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_addSRS_CarrierSwitching_r16_40 = {
	"addSRS-CarrierSwitching-r16",
	"addSRS-CarrierSwitching-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_addSRS_CarrierSwitching_r16_tags_40,
	sizeof(asn_DEF_addSRS_CarrierSwitching_r16_tags_40)
		/sizeof(asn_DEF_addSRS_CarrierSwitching_r16_tags_40[0]) - 1, /* 1 */
	asn_DEF_addSRS_CarrierSwitching_r16_tags_40,	/* Same as above */
	sizeof(asn_DEF_addSRS_CarrierSwitching_r16_tags_40)
		/sizeof(asn_DEF_addSRS_CarrierSwitching_r16_tags_40[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_addSRS_CarrierSwitching_r16_constr_40,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_addSRS_CarrierSwitching_r16_specs_40	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_addSRS_r16_35[] = {
	{ ATF_POINTER, 3, offsetof(struct PhyLayerParameters_v1610__addSRS_r16, addSRS_FrequencyHopping_r16),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_addSRS_FrequencyHopping_r16_36,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"addSRS-FrequencyHopping-r16"
		},
	{ ATF_POINTER, 2, offsetof(struct PhyLayerParameters_v1610__addSRS_r16, addSRS_AntennaSwitching_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_addSRS_AntennaSwitching_r16_38,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"addSRS-AntennaSwitching-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct PhyLayerParameters_v1610__addSRS_r16, addSRS_CarrierSwitching_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_addSRS_CarrierSwitching_r16_40,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"addSRS-CarrierSwitching-r16"
		},
};
static const int asn_MAP_addSRS_r16_oms_35[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_addSRS_r16_tags_35[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_addSRS_r16_tag2el_35[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* addSRS-FrequencyHopping-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* addSRS-AntennaSwitching-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* addSRS-CarrierSwitching-r16 */
};
static asn_SEQUENCE_specifics_t asn_SPC_addSRS_r16_specs_35 = {
	sizeof(struct PhyLayerParameters_v1610__addSRS_r16),
	offsetof(struct PhyLayerParameters_v1610__addSRS_r16, _asn_ctx),
	asn_MAP_addSRS_r16_tag2el_35,
	3,	/* Count of tags in the map */
	asn_MAP_addSRS_r16_oms_35,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_addSRS_r16_35 = {
	"addSRS-r16",
	"addSRS-r16",
	&asn_OP_SEQUENCE,
	asn_DEF_addSRS_r16_tags_35,
	sizeof(asn_DEF_addSRS_r16_tags_35)
		/sizeof(asn_DEF_addSRS_r16_tags_35[0]) - 1, /* 1 */
	asn_DEF_addSRS_r16_tags_35,	/* Same as above */
	sizeof(asn_DEF_addSRS_r16_tags_35)
		/sizeof(asn_DEF_addSRS_r16_tags_35[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_addSRS_r16_35,
	3,	/* Elements count */
	&asn_SPC_addSRS_r16_specs_35	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_virtualCellID_BasicSRS_r16_value2enum_42[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_virtualCellID_BasicSRS_r16_enum2value_42[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_virtualCellID_BasicSRS_r16_specs_42 = {
	asn_MAP_virtualCellID_BasicSRS_r16_value2enum_42,	/* "tag" => N; sorted by tag */
	asn_MAP_virtualCellID_BasicSRS_r16_enum2value_42,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_virtualCellID_BasicSRS_r16_tags_42[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_virtualCellID_BasicSRS_r16_42 = {
	"virtualCellID-BasicSRS-r16",
	"virtualCellID-BasicSRS-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_virtualCellID_BasicSRS_r16_tags_42,
	sizeof(asn_DEF_virtualCellID_BasicSRS_r16_tags_42)
		/sizeof(asn_DEF_virtualCellID_BasicSRS_r16_tags_42[0]) - 1, /* 1 */
	asn_DEF_virtualCellID_BasicSRS_r16_tags_42,	/* Same as above */
	sizeof(asn_DEF_virtualCellID_BasicSRS_r16_tags_42)
		/sizeof(asn_DEF_virtualCellID_BasicSRS_r16_tags_42[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_virtualCellID_BasicSRS_r16_constr_42,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_virtualCellID_BasicSRS_r16_specs_42	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_virtualCellID_AddSRS_r16_value2enum_44[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_virtualCellID_AddSRS_r16_enum2value_44[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_virtualCellID_AddSRS_r16_specs_44 = {
	asn_MAP_virtualCellID_AddSRS_r16_value2enum_44,	/* "tag" => N; sorted by tag */
	asn_MAP_virtualCellID_AddSRS_r16_enum2value_44,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_virtualCellID_AddSRS_r16_tags_44[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_virtualCellID_AddSRS_r16_44 = {
	"virtualCellID-AddSRS-r16",
	"virtualCellID-AddSRS-r16",
	&asn_OP_NativeEnumerated,
	asn_DEF_virtualCellID_AddSRS_r16_tags_44,
	sizeof(asn_DEF_virtualCellID_AddSRS_r16_tags_44)
		/sizeof(asn_DEF_virtualCellID_AddSRS_r16_tags_44[0]) - 1, /* 1 */
	asn_DEF_virtualCellID_AddSRS_r16_tags_44,	/* Same as above */
	sizeof(asn_DEF_virtualCellID_AddSRS_r16_tags_44)
		/sizeof(asn_DEF_virtualCellID_AddSRS_r16_tags_44[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_virtualCellID_AddSRS_r16_constr_44,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_virtualCellID_AddSRS_r16_specs_44	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PhyLayerParameters_v1610_1[] = {
	{ ATF_POINTER, 7, offsetof(struct PhyLayerParameters_v1610, ce_Capabilities_v1610),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_ce_Capabilities_v1610_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ce-Capabilities-v1610"
		},
	{ ATF_POINTER, 6, offsetof(struct PhyLayerParameters_v1610, widebandPRG_Slot_r16),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_widebandPRG_Slot_r16_29,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"widebandPRG-Slot-r16"
		},
	{ ATF_POINTER, 5, offsetof(struct PhyLayerParameters_v1610, widebandPRG_Subslot_r16),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_widebandPRG_Subslot_r16_31,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"widebandPRG-Subslot-r16"
		},
	{ ATF_POINTER, 4, offsetof(struct PhyLayerParameters_v1610, widebandPRG_Subframe_r16),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_widebandPRG_Subframe_r16_33,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"widebandPRG-Subframe-r16"
		},
	{ ATF_POINTER, 3, offsetof(struct PhyLayerParameters_v1610, addSRS_r16),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_addSRS_r16_35,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"addSRS-r16"
		},
	{ ATF_POINTER, 2, offsetof(struct PhyLayerParameters_v1610, virtualCellID_BasicSRS_r16),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_virtualCellID_BasicSRS_r16_42,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"virtualCellID-BasicSRS-r16"
		},
	{ ATF_POINTER, 1, offsetof(struct PhyLayerParameters_v1610, virtualCellID_AddSRS_r16),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_virtualCellID_AddSRS_r16_44,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"virtualCellID-AddSRS-r16"
		},
};
static const int asn_MAP_PhyLayerParameters_v1610_oms_1[] = { 0, 1, 2, 3, 4, 5, 6 };
static const ber_tlv_tag_t asn_DEF_PhyLayerParameters_v1610_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PhyLayerParameters_v1610_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ce-Capabilities-v1610 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* widebandPRG-Slot-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* widebandPRG-Subslot-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* widebandPRG-Subframe-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* addSRS-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* virtualCellID-BasicSRS-r16 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* virtualCellID-AddSRS-r16 */
};
asn_SEQUENCE_specifics_t asn_SPC_PhyLayerParameters_v1610_specs_1 = {
	sizeof(struct PhyLayerParameters_v1610),
	offsetof(struct PhyLayerParameters_v1610, _asn_ctx),
	asn_MAP_PhyLayerParameters_v1610_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_PhyLayerParameters_v1610_oms_1,	/* Optional members */
	7, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PhyLayerParameters_v1610 = {
	"PhyLayerParameters-v1610",
	"PhyLayerParameters-v1610",
	&asn_OP_SEQUENCE,
	asn_DEF_PhyLayerParameters_v1610_tags_1,
	sizeof(asn_DEF_PhyLayerParameters_v1610_tags_1)
		/sizeof(asn_DEF_PhyLayerParameters_v1610_tags_1[0]), /* 1 */
	asn_DEF_PhyLayerParameters_v1610_tags_1,	/* Same as above */
	sizeof(asn_DEF_PhyLayerParameters_v1610_tags_1)
		/sizeof(asn_DEF_PhyLayerParameters_v1610_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_PhyLayerParameters_v1610_1,
	7,	/* Elements count */
	&asn_SPC_PhyLayerParameters_v1610_specs_1	/* Additional specs */
};

