/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_RMTC_ConfigNR_r16_H_
#define	_RMTC_ConfigNR_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include "ARFCN-ValueNR-r15.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RMTC_ConfigNR_r16__rmtc_PeriodicityNR_r16 {
	RMTC_ConfigNR_r16__rmtc_PeriodicityNR_r16_ms40	= 0,
	RMTC_ConfigNR_r16__rmtc_PeriodicityNR_r16_ms80	= 1,
	RMTC_ConfigNR_r16__rmtc_PeriodicityNR_r16_ms160	= 2,
	RMTC_ConfigNR_r16__rmtc_PeriodicityNR_r16_ms320	= 3,
	RMTC_ConfigNR_r16__rmtc_PeriodicityNR_r16_ms640	= 4
} e_RMTC_ConfigNR_r16__rmtc_PeriodicityNR_r16;
typedef enum RMTC_ConfigNR_r16__measDurationNR_r16 {
	RMTC_ConfigNR_r16__measDurationNR_r16_sym1	= 0,
	RMTC_ConfigNR_r16__measDurationNR_r16_sym14or12	= 1,
	RMTC_ConfigNR_r16__measDurationNR_r16_sym28or24	= 2,
	RMTC_ConfigNR_r16__measDurationNR_r16_sym42or36	= 3,
	RMTC_ConfigNR_r16__measDurationNR_r16_sym70or60	= 4
} e_RMTC_ConfigNR_r16__measDurationNR_r16;
typedef enum RMTC_ConfigNR_r16__refSCS_CP_NR_r16 {
	RMTC_ConfigNR_r16__refSCS_CP_NR_r16_kHz15	= 0,
	RMTC_ConfigNR_r16__refSCS_CP_NR_r16_kHz30	= 1,
	RMTC_ConfigNR_r16__refSCS_CP_NR_r16_kHz60_NCP	= 2,
	RMTC_ConfigNR_r16__refSCS_CP_NR_r16_kHz60_ECP	= 3
} e_RMTC_ConfigNR_r16__refSCS_CP_NR_r16;
typedef enum RMTC_ConfigNR_r16__ext1__rmtc_BandwidthNR_r17 {
	RMTC_ConfigNR_r16__ext1__rmtc_BandwidthNR_r17_mhz100	= 0,
	RMTC_ConfigNR_r16__ext1__rmtc_BandwidthNR_r17_mhz400	= 1,
	RMTC_ConfigNR_r16__ext1__rmtc_BandwidthNR_r17_mhz800	= 2,
	RMTC_ConfigNR_r16__ext1__rmtc_BandwidthNR_r17_mhz1600	= 3,
	RMTC_ConfigNR_r16__ext1__rmtc_BandwidthNR_r17_mhz2000	= 4
} e_RMTC_ConfigNR_r16__ext1__rmtc_BandwidthNR_r17;
typedef enum RMTC_ConfigNR_r16__ext1__measDurationNR_r17 {
	RMTC_ConfigNR_r16__ext1__measDurationNR_r17_sym140	= 0,
	RMTC_ConfigNR_r16__ext1__measDurationNR_r17_sym560	= 1,
	RMTC_ConfigNR_r16__ext1__measDurationNR_r17_sym1120	= 2
} e_RMTC_ConfigNR_r16__ext1__measDurationNR_r17;
typedef enum RMTC_ConfigNR_r16__ext1__refSCS_CP_NR_r17 {
	RMTC_ConfigNR_r16__ext1__refSCS_CP_NR_r17_kHz120	= 0,
	RMTC_ConfigNR_r16__ext1__refSCS_CP_NR_r17_kHz480	= 1,
	RMTC_ConfigNR_r16__ext1__refSCS_CP_NR_r17_kHz960	= 2
} e_RMTC_ConfigNR_r16__ext1__refSCS_CP_NR_r17;

/* RMTC-ConfigNR-r16 */
typedef struct RMTC_ConfigNR_r16 {
	long	 rmtc_PeriodicityNR_r16;
	long	*rmtc_SubframeOffsetNR_r16;	/* OPTIONAL */
	long	 measDurationNR_r16;
	ARFCN_ValueNR_r15_t	 rmtc_FrequencyNR_r16;
	long	 refSCS_CP_NR_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct RMTC_ConfigNR_r16__ext1 {
		long	*rmtc_BandwidthNR_r17;	/* OPTIONAL */
		long	*measDurationNR_r17;	/* OPTIONAL */
		long	*refSCS_CP_NR_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RMTC_ConfigNR_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_rmtc_PeriodicityNR_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_measDurationNR_r16_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_refSCS_CP_NR_r16_16;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_rmtc_BandwidthNR_r17_23;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_measDurationNR_r17_29;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_refSCS_CP_NR_r17_33;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RMTC_ConfigNR_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_RMTC_ConfigNR_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_RMTC_ConfigNR_r16_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _RMTC_ConfigNR_r16_H_ */
#include <asn_internal.h>
