/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_RRCConnectionSetupComplete_v1610_IEs_H_
#define	_RRCConnectionSetupComplete_v1610_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "PUR-ConfigID-r16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCConnectionSetupComplete_v1610_IEs__rlos_Request_r16 {
	RRCConnectionSetupComplete_v1610_IEs__rlos_Request_r16_true	= 0
} e_RRCConnectionSetupComplete_v1610_IEs__rlos_Request_r16;
typedef enum RRCConnectionSetupComplete_v1610_IEs__cp_CIoT_5GS_Optimisation_r16 {
	RRCConnectionSetupComplete_v1610_IEs__cp_CIoT_5GS_Optimisation_r16_true	= 0
} e_RRCConnectionSetupComplete_v1610_IEs__cp_CIoT_5GS_Optimisation_r16;
typedef enum RRCConnectionSetupComplete_v1610_IEs__up_CIoT_5GS_Optimisation_r16 {
	RRCConnectionSetupComplete_v1610_IEs__up_CIoT_5GS_Optimisation_r16_true	= 0
} e_RRCConnectionSetupComplete_v1610_IEs__up_CIoT_5GS_Optimisation_r16;
typedef enum RRCConnectionSetupComplete_v1610_IEs__lte_M_r16 {
	RRCConnectionSetupComplete_v1610_IEs__lte_M_r16_true	= 0
} e_RRCConnectionSetupComplete_v1610_IEs__lte_M_r16;
typedef enum RRCConnectionSetupComplete_v1610_IEs__iab_NodeIndication_r16 {
	RRCConnectionSetupComplete_v1610_IEs__iab_NodeIndication_r16_true	= 0
} e_RRCConnectionSetupComplete_v1610_IEs__iab_NodeIndication_r16;

/* Forward declarations */
struct RRCConnectionSetupComplete_v1690_IEs;

/* RRCConnectionSetupComplete-v1610-IEs */
typedef struct RRCConnectionSetupComplete_v1610_IEs {
	long	*rlos_Request_r16;	/* OPTIONAL */
	long	*cp_CIoT_5GS_Optimisation_r16;	/* OPTIONAL */
	long	*up_CIoT_5GS_Optimisation_r16;	/* OPTIONAL */
	PUR_ConfigID_r16_t	*pur_ConfigID_r16;	/* OPTIONAL */
	long	*lte_M_r16;	/* OPTIONAL */
	long	*iab_NodeIndication_r16;	/* OPTIONAL */
	struct RRCConnectionSetupComplete_v1690_IEs	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionSetupComplete_v1610_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_rlos_Request_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_cp_CIoT_5GS_Optimisation_r16_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_up_CIoT_5GS_Optimisation_r16_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_lte_M_r16_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_iab_NodeIndication_r16_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionSetupComplete_v1610_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionSetupComplete_v1610_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionSetupComplete_v1610_IEs_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionSetupComplete_v1610_IEs_H_ */
#include <asn_internal.h>
