/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_RRCConnectionResume_v1700_IEs_H_
#define	_RRCConnectionResume_v1700_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCConnectionResume_v1700_IEs__scg_State_r17 {
	RRCConnectionResume_v1700_IEs__scg_State_r17_deactivated	= 0
} e_RRCConnectionResume_v1700_IEs__scg_State_r17;

/* RRCConnectionResume-v1700-IEs */
typedef struct RRCConnectionResume_v1700_IEs {
	long	*scg_State_r17;	/* OPTIONAL */
	struct RRCConnectionResume_v1700_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionResume_v1700_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_scg_State_r17_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionResume_v1700_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionResume_v1700_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionResume_v1700_IEs_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionResume_v1700_IEs_H_ */
#include <asn_internal.h>
