/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_SCellToAddMod_r16_H_
#define	_SCellToAddMod_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SCellIndex-r13.h"
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include "PhysCellId.h"
#include "ARFCN-ValueEUTRA-r9.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SCellToAddMod_r16__sCellState_r16 {
	SCellToAddMod_r16__sCellState_r16_activated	= 0,
	SCellToAddMod_r16__sCellState_r16_dormant	= 1
} e_SCellToAddMod_r16__sCellState_r16;

/* Forward declarations */
struct RadioResourceConfigCommonSCell_r10;
struct RadioResourceConfigDedicatedSCell_r10;
struct AntennaInfoDedicated_v10i0;

/* SCellToAddMod-r16 */
typedef struct SCellToAddMod_r16 {
	SCellIndex_r13_t	 sCellIndex_r16;
	struct SCellToAddMod_r16__cellIdentification_r16 {
		PhysCellId_t	 physCellId_r16;
		ARFCN_ValueEUTRA_r9_t	 dl_CarrierFreq_r16;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *cellIdentification_r16;
	struct RadioResourceConfigCommonSCell_r10	*radioResourceConfigCommonSCell_r16;	/* OPTIONAL */
	struct RadioResourceConfigDedicatedSCell_r10	*radioResourceConfigDedicatedSCell_r16;	/* OPTIONAL */
	struct AntennaInfoDedicated_v10i0	*antennaInfoDedicatedSCell_r16;	/* OPTIONAL */
	long	*srs_SwitchFromServCellIndex_r16;	/* OPTIONAL */
	long	*sCellState_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SCellToAddMod_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_sCellState_r16_10;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SCellToAddMod_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_SCellToAddMod_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_SCellToAddMod_r16_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _SCellToAddMod_r16_H_ */
#include <asn_internal.h>
