/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_SCGFailureInformationNR_r15_H_
#define	_SCGFailureInformationNR_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SCGFailureInformationNR-r15-IEs.h"
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SCGFailureInformationNR_r15__criticalExtensions_PR {
	SCGFailureInformationNR_r15__criticalExtensions_PR_NOTHING,	/* No components present */
	SCGFailureInformationNR_r15__criticalExtensions_PR_c1,
	SCGFailureInformationNR_r15__criticalExtensions_PR_criticalExtensionsFuture
} SCGFailureInformationNR_r15__criticalExtensions_PR;
typedef enum SCGFailureInformationNR_r15__criticalExtensions__c1_PR {
	SCGFailureInformationNR_r15__criticalExtensions__c1_PR_NOTHING,	/* No components present */
	SCGFailureInformationNR_r15__criticalExtensions__c1_PR_scgFailureInformationNR_r15,
	SCGFailureInformationNR_r15__criticalExtensions__c1_PR_spare3,
	SCGFailureInformationNR_r15__criticalExtensions__c1_PR_spare2,
	SCGFailureInformationNR_r15__criticalExtensions__c1_PR_spare1
} SCGFailureInformationNR_r15__criticalExtensions__c1_PR;

/* SCGFailureInformationNR-r15 */
typedef struct SCGFailureInformationNR_r15 {
	struct SCGFailureInformationNR_r15__criticalExtensions {
		SCGFailureInformationNR_r15__criticalExtensions_PR present;
		union SCGFailureInformationNR_r15__criticalExtensions_u {
			struct SCGFailureInformationNR_r15__criticalExtensions__c1 {
				SCGFailureInformationNR_r15__criticalExtensions__c1_PR present;
				union SCGFailureInformationNR_r15__criticalExtensions__c1_u {
					SCGFailureInformationNR_r15_IEs_t	 scgFailureInformationNR_r15;
					NULL_t	 spare3;
					NULL_t	 spare2;
					NULL_t	 spare1;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} c1;
			struct SCGFailureInformationNR_r15__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SCGFailureInformationNR_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SCGFailureInformationNR_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_SCGFailureInformationNR_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_SCGFailureInformationNR_r15_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _SCGFailureInformationNR_r15_H_ */
#include <asn_internal.h>
