/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_SIB_Type_v12j0_H_
#define	_SIB_Type_v12j0_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SIB_Type_v12j0 {
	SIB_Type_v12j0_sibType19_v1250	= 0,
	SIB_Type_v12j0_sibType20_v1310	= 1,
	SIB_Type_v12j0_sibType21_v1430	= 2,
	SIB_Type_v12j0_sibType24_v1530	= 3,
	SIB_Type_v12j0_sibType25_v1530	= 4,
	SIB_Type_v12j0_sibType26_v1530	= 5,
	SIB_Type_v12j0_sibType26a_v1610	= 6,
	SIB_Type_v12j0_sibType27_v1610	= 7,
	SIB_Type_v12j0_sibType28_v1610	= 8,
	SIB_Type_v12j0_sibType29_v1610	= 9,
	SIB_Type_v12j0_sibType30_v1700	= 10,
	SIB_Type_v12j0_sibType31_v1700	= 11,
	SIB_Type_v12j0_sibType32_v1700	= 12,
	SIB_Type_v12j0_spare3	= 13,
	SIB_Type_v12j0_spare2	= 14,
	SIB_Type_v12j0_spare1	= 15
	/*
	 * Enumeration is extensible
	 */
} e_SIB_Type_v12j0;

/* SIB-Type-v12j0 */
typedef long	 SIB_Type_v12j0_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SIB_Type_v12j0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SIB_Type_v12j0;
extern const asn_INTEGER_specifics_t asn_SPC_SIB_Type_v12j0_specs_1;
asn_struct_free_f SIB_Type_v12j0_free;
asn_struct_print_f SIB_Type_v12j0_print;
asn_constr_check_f SIB_Type_v12j0_constraint;
ber_type_decoder_f SIB_Type_v12j0_decode_ber;
der_type_encoder_f SIB_Type_v12j0_encode_der;
xer_type_decoder_f SIB_Type_v12j0_decode_xer;
xer_type_encoder_f SIB_Type_v12j0_encode_xer;
jer_type_encoder_f SIB_Type_v12j0_encode_jer;
per_type_decoder_f SIB_Type_v12j0_decode_uper;
per_type_encoder_f SIB_Type_v12j0_encode_uper;
per_type_decoder_f SIB_Type_v12j0_decode_aper;
per_type_encoder_f SIB_Type_v12j0_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SIB_Type_v12j0_H_ */
#include <asn_internal.h>
