/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_SL_OffsetIndicatorSync_v1430_H_
#define	_SL_OffsetIndicatorSync_v1430_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SL-OffsetIndicatorSync-v1430 */
typedef long	 SL_OffsetIndicatorSync_v1430_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SL_OffsetIndicatorSync_v1430_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SL_OffsetIndicatorSync_v1430;
asn_struct_free_f SL_OffsetIndicatorSync_v1430_free;
asn_struct_print_f SL_OffsetIndicatorSync_v1430_print;
asn_constr_check_f SL_OffsetIndicatorSync_v1430_constraint;
ber_type_decoder_f SL_OffsetIndicatorSync_v1430_decode_ber;
der_type_encoder_f SL_OffsetIndicatorSync_v1430_encode_der;
xer_type_decoder_f SL_OffsetIndicatorSync_v1430_decode_xer;
xer_type_encoder_f SL_OffsetIndicatorSync_v1430_encode_xer;
jer_type_encoder_f SL_OffsetIndicatorSync_v1430_encode_jer;
per_type_decoder_f SL_OffsetIndicatorSync_v1430_decode_uper;
per_type_encoder_f SL_OffsetIndicatorSync_v1430_encode_uper;
per_type_decoder_f SL_OffsetIndicatorSync_v1430_decode_aper;
per_type_encoder_f SL_OffsetIndicatorSync_v1430_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SL_OffsetIndicatorSync_v1430_H_ */
#include <asn_internal.h>
