/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_SPUCCH_Config_r15_H_
#define	_SPUCCH_Config_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SPUCCH_Config_r15_PR {
	SPUCCH_Config_r15_PR_NOTHING,	/* No components present */
	SPUCCH_Config_r15_PR_release,
	SPUCCH_Config_r15_PR_setup
} SPUCCH_Config_r15_PR;
typedef enum SPUCCH_Config_r15__setup__twoAntennaPortActivatedSPUCCH_Format1a1b_r15 {
	SPUCCH_Config_r15__setup__twoAntennaPortActivatedSPUCCH_Format1a1b_r15_true	= 0
} e_SPUCCH_Config_r15__setup__twoAntennaPortActivatedSPUCCH_Format1a1b_r15;

/* Forward declarations */
struct SPUCCH_Set_r15;

/* SPUCCH-Config-r15 */
typedef struct SPUCCH_Config_r15 {
	SPUCCH_Config_r15_PR present;
	union SPUCCH_Config_r15_u {
		NULL_t	 release;
		struct SPUCCH_Config_r15__setup {
			struct SPUCCH_Set_r15	*spucch_Set_r15;	/* OPTIONAL */
			long	*twoAntennaPortActivatedSPUCCH_Format1a1b_r15;	/* OPTIONAL */
			struct SPUCCH_Config_r15__setup__dummy {
				struct SPUCCH_Config_r15__setup__dummy__n3SPUCCH_AN_List_r15 {
					A_SEQUENCE_OF(long) list;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} n3SPUCCH_AN_List_r15;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} dummy;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SPUCCH_Config_r15_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_twoAntennaPortActivatedSPUCCH_Format1a1b_r15_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SPUCCH_Config_r15;
extern asn_CHOICE_specifics_t asn_SPC_SPUCCH_Config_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_SPUCCH_Config_r15_1[2];
extern asn_per_constraints_t asn_PER_type_SPUCCH_Config_r15_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SPUCCH_Config_r15_H_ */
#include <asn_internal.h>
