/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_SSB_PositionQCL_CellsToAddNR_r17_H_
#define	_SSB_PositionQCL_CellsToAddNR_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PhysCellIdNR-r15.h"
#include "SSB-PositionQCL-RelationNR-r17.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SSB-PositionQCL-CellsToAddNR-r17 */
typedef struct SSB_PositionQCL_CellsToAddNR_r17 {
	PhysCellIdNR_r15_t	 physCellIdNR_r17;
	SSB_PositionQCL_RelationNR_r17_t	 ssb_PositionQCL_NR_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SSB_PositionQCL_CellsToAddNR_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SSB_PositionQCL_CellsToAddNR_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_SSB_PositionQCL_CellsToAddNR_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_SSB_PositionQCL_CellsToAddNR_r17_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SSB_PositionQCL_CellsToAddNR_r17_H_ */
#include <asn_internal.h>
