/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_SubframeAssignment_r15_H_
#define	_SubframeAssignment_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SubframeAssignment_r15 {
	SubframeAssignment_r15_sa0	= 0,
	SubframeAssignment_r15_sa1	= 1,
	SubframeAssignment_r15_sa2	= 2,
	SubframeAssignment_r15_sa3	= 3,
	SubframeAssignment_r15_sa4	= 4,
	SubframeAssignment_r15_sa5	= 5,
	SubframeAssignment_r15_sa6	= 6
} e_SubframeAssignment_r15;

/* SubframeAssignment-r15 */
typedef long	 SubframeAssignment_r15_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SubframeAssignment_r15_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SubframeAssignment_r15;
extern const asn_INTEGER_specifics_t asn_SPC_SubframeAssignment_r15_specs_1;
asn_struct_free_f SubframeAssignment_r15_free;
asn_struct_print_f SubframeAssignment_r15_print;
asn_constr_check_f SubframeAssignment_r15_constraint;
ber_type_decoder_f SubframeAssignment_r15_decode_ber;
der_type_encoder_f SubframeAssignment_r15_encode_der;
xer_type_decoder_f SubframeAssignment_r15_decode_xer;
xer_type_encoder_f SubframeAssignment_r15_encode_xer;
jer_type_encoder_f SubframeAssignment_r15_encode_jer;
per_type_decoder_f SubframeAssignment_r15_decode_uper;
per_type_encoder_f SubframeAssignment_r15_encode_uper;
per_type_decoder_f SubframeAssignment_r15_decode_aper;
per_type_encoder_f SubframeAssignment_r15_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SubframeAssignment_r15_H_ */
#include <asn_internal.h>
