/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#ifndef	_T_ReorderingExt_r17_H_
#define	_T_ReorderingExt_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum T_ReorderingExt_r17 {
	T_ReorderingExt_r17_ms2200	= 0,
	T_ReorderingExt_r17_ms3200	= 1
} e_T_ReorderingExt_r17;

/* T-ReorderingExt-r17 */
typedef long	 T_ReorderingExt_r17_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_T_ReorderingExt_r17_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_T_ReorderingExt_r17;
extern const asn_INTEGER_specifics_t asn_SPC_T_ReorderingExt_r17_specs_1;
asn_struct_free_f T_ReorderingExt_r17_free;
asn_struct_print_f T_ReorderingExt_r17_print;
asn_constr_check_f T_ReorderingExt_r17_constraint;
ber_type_decoder_f T_ReorderingExt_r17_decode_ber;
der_type_encoder_f T_ReorderingExt_r17_encode_der;
xer_type_decoder_f T_ReorderingExt_r17_decode_xer;
xer_type_encoder_f T_ReorderingExt_r17_encode_xer;
jer_type_encoder_f T_ReorderingExt_r17_encode_jer;
per_type_decoder_f T_ReorderingExt_r17_decode_uper;
per_type_encoder_f T_ReorderingExt_r17_encode_uper;
per_type_decoder_f T_ReorderingExt_r17_decode_aper;
per_type_encoder_f T_ReorderingExt_r17_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _T_ReorderingExt_r17_H_ */
#include <asn_internal.h>
