/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -S /home/koluchiy/fork_asn1c/skeletons -D src -pdu=RRCConnectionRequest -no-gen-OER -fcompound-names -no-gen-example -fno-include-deps`
 */

#include "UEInformationResponse-r9-IEs.h"

#include "RACH-Report-r16.h"
#include "RLF-Report-r9.h"
#include "UEInformationResponse-v930-IEs.h"
asn_TYPE_member_t asn_MBR_UEInformationResponse_r9_IEs_1[] = {
	{ ATF_POINTER, 3, offsetof(struct UEInformationResponse_r9_IEs, rach_Report_r9),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RACH_Report_r16,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"rach-Report-r9"
		},
	{ ATF_POINTER, 2, offsetof(struct UEInformationResponse_r9_IEs, rlf_Report_r9),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RLF_Report_r9,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"rlf-Report-r9"
		},
	{ ATF_POINTER, 1, offsetof(struct UEInformationResponse_r9_IEs, nonCriticalExtension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UEInformationResponse_v930_IEs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nonCriticalExtension"
		},
};
static const int asn_MAP_UEInformationResponse_r9_IEs_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_UEInformationResponse_r9_IEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UEInformationResponse_r9_IEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rach-Report-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rlf-Report-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* nonCriticalExtension */
};
asn_SEQUENCE_specifics_t asn_SPC_UEInformationResponse_r9_IEs_specs_1 = {
	sizeof(struct UEInformationResponse_r9_IEs),
	offsetof(struct UEInformationResponse_r9_IEs, _asn_ctx),
	asn_MAP_UEInformationResponse_r9_IEs_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_UEInformationResponse_r9_IEs_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UEInformationResponse_r9_IEs = {
	"UEInformationResponse-r9-IEs",
	"UEInformationResponse-r9-IEs",
	&asn_OP_SEQUENCE,
	asn_DEF_UEInformationResponse_r9_IEs_tags_1,
	sizeof(asn_DEF_UEInformationResponse_r9_IEs_tags_1)
		/sizeof(asn_DEF_UEInformationResponse_r9_IEs_tags_1[0]), /* 1 */
	asn_DEF_UEInformationResponse_r9_IEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_UEInformationResponse_r9_IEs_tags_1)
		/sizeof(asn_DEF_UEInformationResponse_r9_IEs_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_UEInformationResponse_r9_IEs_1,
	3,	/* Elements count */
	&asn_SPC_UEInformationResponse_r9_IEs_specs_1	/* Additional specs */
};

